HCChallengerChallenges = {
    {
        id = "STANDARD",
        name = "Standard / No challenge",
        icon = "Interface\\Icons\\INV_Misc_Map_01",
        rules = "Normal leveling route without a challenge-specific restriction.",
        advice = "Use this for ordinary quest, travel and grind routes.",
    },
    {
        id = "SLOW_STEADY",
        name = "Slow & Steady",
        icon = "Interface\\Icons\\INV_Misc_PocketWatch_01",
        rules = "Creature kill experience is shown as 0.5x. The pictured rules also describe an experience loss on non-PvP death.",
        advice = "Prefer dense quest chains, safe travel and low-risk objectives over pure grinding.",
    },
    {
        id = "TOGETHER_FOREVER",
        name = "Together Forever",
        icon = "Interface\\Icons\\Spell_Holy_PrayerOfHealing02",
        rules = "A fellowship of up to four is formed before level 2. Mob and quest experience requires fellowship members nearby.",
        advice = "Write regroup points, shared turn-ins and explicit wait steps into the route.",
    },
    {
        id = "HARDCORE",
        name = "Hardcore Mode",
        icon = "Interface\\Icons\\INV_Misc_Bone_HumanSkull_01",
        rules = "Do not die. The pictured rules restrict mail, trade and grouping to nearby levels and remove auction house and dungeon finder access.",
        advice = "Use Safety steps for escape items, dangerous pulls and regroup points.",
    },
    {
        id = "WAR_MODE",
        name = "War Mode",
        icon = "Interface\\Icons\\Ability_DualWield",
        rules = "Permanently PvP flagged; the pictured rules state bonus experience outside dungeons and in battlegrounds.",
        advice = "Mark hostile hubs, alternate roads and protected hand-in paths.",
    },
    {
        id = "EXHAUSTION",
        name = "Exhaustion",
        icon = "Interface\\Icons\\Spell_Nature_Sleep",
        rules = "No rested experience bonus. The pictured rules also state doubled weapon skill learning rate.",
        advice = "Do not assume rested XP when estimating level transitions.",
    },
    {
        id = "TRAVELING_CRAFTSMAN",
        name = "Traveling Craftsman",
        icon = "Interface\\Icons\\Trade_BlackSmithing",
        rules = "Until level 60, only self-crafted gear may be equipped; fishing poles are excluded in the pictured rules.",
        advice = "Add Train, Craft and material collection steps before gear-dependent sections.",
    },
    {
        id = "WAY_SAMURAI",
        name = "Way of the Samurai",
        icon = "Interface\\Icons\\INV_Sword_36",
        rules = "Available to Warrior, Paladin, Hunter and Rogue. Weapon choices are restricted to katana-style swords, thrown weapons and profession tools.",
        advice = "Call out weapon vendors, trainers and replacement breakpoints.",
    },
    {
        id = "VAGRANTS_ENDEAVOR",
        name = "Vagrant's Endeavor",
        icon = "Interface\\Icons\\INV_Shirt_Grey_01",
        rules = "Only unenchanted poor (grey) or common (white) quality gear may be equipped on the journey to maximum level.",
        advice = "Avoid guide steps that assume uncommon quest rewards are equipped.",
    },
    {
        id = "BREWMASTER",
        name = "Brewmaster",
        icon = "Interface\\Icons\\INV_Drink_05",
        rules = "Experience is earned only while completely smashed according to the pictured rules.",
        advice = "Add drink restock checks before quest clusters and long grinds.",
    },
    {
        id = "TRIAL_HEROISM",
        name = "Trial of Heroism",
        icon = "Interface\\Icons\\Ability_Warrior_InnerRage",
        rules = "Below level 58, only kills against enemies at least 3 levels above you grant experience. Quest experience is permitted; exploration and battleground experience are disabled.",
        advice = "Record mob level ranges on Kill/Grind steps. The guide checks the current target against player level + 3, but never targets or attacks automatically.",
    },
    {
        id = "BOARING_ADVENTURE",
        name = "Boaring Adventure",
        icon = "Interface\\Icons\\Ability_Hunter_Pet_Boar",
        rules = "Only killing boars grants experience according to the pictured rules.",
        advice = "Use Grind steps with exact boar names, level ranges, respawn notes and safe fallback camps.",
    },
    {
        id = "LUNATIC",
        name = "Lunatic",
        icon = "Interface\\Icons\\INV_Misc_Food_19",
        rules = "You earn no experience and remain level 1. The pictured challenge is based on exploration and collection achievements.",
        advice = "Build exploration routes with Travel, Safety and Note steps instead of level breakpoints.",
    },
}
