local HC=HCChallenger
HC.Frames={}
HC.ROUTE_ROWS=7
HC.STEP_ROWS=6
HC.COMMUNITY_ROWS=9
local BACKDROP={bgFile="Interface\\DialogFrame\\UI-DialogBox-Background",edgeFile="Interface\\DialogFrame\\UI-DialogBox-Border",tile=1,tileSize=32,edgeSize=32,insets={left=10,right=10,top=10,bottom=10}}
local PANEL={bgFile="Interface\\Tooltips\\UI-Tooltip-Background",edgeFile="Interface\\Tooltips\\UI-Tooltip-Border",tile=1,tileSize=16,edgeSize=14,insets={left=3,right=3,top=3,bottom=3}}
local function Text(parent,value,font,r,g,b)local f=parent:CreateFontString(nil,"OVERLAY",font or"GameFontHighlightSmall");f:SetText(value or"");if r then f:SetTextColor(r,g,b)end;return f end
local function Button(parent,value,width)local b=CreateFrame("Button",nil,parent,"UIPanelButtonTemplate");b:SetWidth(width or 90);b:SetHeight(23);b:SetText(value);return b end
local function Edit(parent,width,maxLetters)local e=CreateFrame("EditBox",nil,parent,"InputBoxTemplate");e:SetWidth(width);e:SetHeight(24);e:SetAutoFocus(nil);e:SetMaxLetters(maxLetters or 80);e:SetScript("OnEscapePressed",function()this:ClearFocus()end);e:SetScript("OnEnterPressed",function()this:ClearFocus()end);return e end
local function Panel(parent)local p=CreateFrame("Frame",nil,parent);p:SetBackdrop(PANEL);p:SetBackdropColor(.02,.02,.02,.96);p:SetBackdropBorderColor(.38,.31,.17,1);return p end

function HC:SetMinimapAngle(angle)if self.Frames.minimap then self.Frames.minimap:ClearAllPoints();self.Frames.minimap:SetPoint("CENTER",Minimap,"CENTER",math.cos(angle or-.2)*80,math.sin(angle or-.2)*80)end end
function HC:CreateMinimapButton()
 local b=CreateFrame("Button","HCChallengerMinimapButton",Minimap);b:SetWidth(31);b:SetHeight(31);b:SetFrameStrata("MEDIUM");b:SetFrameLevel(Minimap:GetFrameLevel()+8);b:RegisterForClicks("LeftButtonUp");b:RegisterForDrag("LeftButton")
 local bg=b:CreateTexture(nil,"BACKGROUND");bg:SetTexture("Interface\\Minimap\\UI-Minimap-Background");bg:SetWidth(24);bg:SetHeight(24);bg:SetPoint("CENTER",b,"CENTER",0,0)
 local icon=b:CreateTexture(nil,"ARTWORK");icon:SetTexture("Interface\\Icons\\INV_Misc_Note_01");icon:SetWidth(20);icon:SetHeight(20);icon:SetPoint("CENTER",b,"CENTER",0,0);icon:SetTexCoord(.08,.92,.08,.92)
 local border=b:CreateTexture(nil,"OVERLAY");border:SetTexture("Interface\\Minimap\\MiniMap-TrackingBorder");border:SetWidth(52);border:SetHeight(52);border:SetPoint("CENTER",b,"CENTER",10,-9)
 b:SetScript("OnClick",function()if this.wasDragged then this.wasDragged=nil else HC:Toggle()end end);b:SetScript("OnDragStart",function()this.dragging=1 end);b:SetScript("OnDragStop",function()if this.dragging then this.dragging=nil;this.wasDragged=1 end end)
 b:SetScript("OnUpdate",function()if this.dragging and HC.DB then local s=Minimap:GetEffectiveScale();local x,y=GetCursorPosition();x=x/s;y=y/s;local cx,cy=Minimap:GetCenter();HC.DB.settings.minimapAngle=math.atan2(y-cy,x-cx);HC:SetMinimapAngle(HC.DB.settings.minimapAngle)end end)
 b:SetScript("OnEnter",function()GameTooltip:SetOwner(this,"ANCHOR_LEFT");GameTooltip:SetText(HC.COLORED_NAME);GameTooltip:AddLine("Click to open challenge routes.",1,1,1);GameTooltip:AddLine("Drag to move this icon.",.65,.85,1);GameTooltip:Show()end);b:SetScript("OnLeave",function()GameTooltip:Hide()end);self.Frames.minimap=b
end
function HC:CreateMyPanel(parent)
 local root=CreateFrame("Frame",nil,parent);root:SetAllPoints(parent);local left=Panel(root);left:SetPoint("TOPLEFT",root,"TOPLEFT",0,0);left:SetWidth(218);left:SetHeight(430);local head=Text(left,"MY ROUTES","GameFontNormal",1,.82,.2);head:SetPoint("TOP",left,"TOP",0,-10);left.rows={};local i
 for i=1,self.ROUTE_ROWS do local r=CreateFrame("Button",nil,left);r:SetWidth(194);r:SetHeight(30);r:SetPoint("TOPLEFT",left,"TOPLEFT",12,-34-((i-1)*32));r:SetBackdrop(PANEL);r:SetBackdropColor(math.mod(i,2)==0 and .05 or .025,.025,.02,.8);r.name=Text(r,"");r.name:SetPoint("TOPLEFT",r,"TOPLEFT",7,-5);r.name:SetWidth(180);r.name:SetJustifyH("LEFT");r.meta=Text(r,"","GameFontDisableSmall",.62,.59,.53);r.meta:SetPoint("TOPLEFT",r.name,"BOTTOMLEFT",0,-1);r:SetScript("OnClick",function()if this.routeId then HC:SelectRoute(this.routeId)end end);left.rows[i]=r end
 local newer=Button(left,"Newer",64);newer:SetPoint("BOTTOMLEFT",left,"BOTTOMLEFT",10,45);newer:SetScript("OnClick",function()HC.State.routeOffset=HC.State.routeOffset-HC.ROUTE_ROWS;if HC.State.routeOffset<0 then HC.State.routeOffset=0 end;HC:RefreshUI()end);local older=Button(left,"Older",64);older:SetPoint("LEFT",newer,"RIGHT",5,0);older:SetScript("OnClick",function()HC.State.routeOffset=HC.State.routeOffset+HC.ROUTE_ROWS;HC:RefreshUI()end);local delete=Button(left,"Delete",64);delete:SetPoint("LEFT",older,"RIGHT",5,0);delete:SetScript("OnClick",function()HC:DeleteSelectedRoute()end)
 local newRoute=Button(left,"New route",90);newRoute:SetPoint("BOTTOM",left,"BOTTOM",0,12);newRoute:SetScript("OnClick",function()local challenge=HCChallengerChallenges[HC.State.challengeIndex]or HCChallengerChallenges[1];HC:CreateRoute("New "..challenge.name.." route",challenge.id)end)

 local meta=Panel(root);meta:SetPoint("TOPLEFT",root,"TOPLEFT",228,0);meta:SetWidth(672);meta:SetHeight(126);local mh=Text(meta,"ROUTE DETAILS","GameFontNormal",1,.82,.2);mh:SetPoint("TOPLEFT",meta,"TOPLEFT",10,-9);meta.name=Edit(meta,245,48);meta.name:SetPoint("TOPLEFT",meta,"TOPLEFT",10,-31);meta.challenge=Button(meta,"Challenge",170);meta.challenge:SetPoint("LEFT",meta.name,"RIGHT",7,0);meta.challenge:SetScript("OnClick",function()HC.State.challengeIndex=HC.State.challengeIndex+1;if HC.State.challengeIndex>table.getn(HCChallengerChallenges)then HC.State.challengeIndex=1 end;this:SetText(HCChallengerChallenges[HC.State.challengeIndex].name)end);meta.faction=Button(meta,"Both",82);meta.faction:SetPoint("LEFT",meta.challenge,"RIGHT",6,0);meta.faction:SetScript("OnClick",function()HC.State.factionIndex=HC.State.factionIndex+1;if HC.State.factionIndex>table.getn(HC.Factions)then HC.State.factionIndex=1 end;this:SetText(HC.Factions[HC.State.factionIndex])end);meta.class=Button(meta,"Any",82);meta.class:SetPoint("LEFT",meta.faction,"RIGHT",6,0);meta.class:SetScript("OnClick",function()HC.State.classIndex=HC.State.classIndex+1;if HC.State.classIndex>table.getn(HC.Classes)then HC.State.classIndex=1 end;this:SetText(HC.Classes[HC.State.classIndex])end)
 local dl=Text(meta,"Description","GameFontDisableSmall",.65,.61,.54);dl:SetPoint("TOPLEFT",meta,"TOPLEFT",12,-65);meta.description=Edit(meta,350,120);meta.description:SetPoint("TOPLEFT",meta,"TOPLEFT",83,-60);local ll=Text(meta,"Levels","GameFontDisableSmall",.65,.61,.54);ll:SetPoint("LEFT",meta.description,"RIGHT",8,0);meta.minLevel=Edit(meta,35,2);meta.minLevel:SetPoint("LEFT",ll,"RIGHT",6,0);local dash=Text(meta,"-");dash:SetPoint("LEFT",meta.minLevel,"RIGHT",4,0);meta.maxLevel=Edit(meta,35,2);meta.maxLevel:SetPoint("LEFT",dash,"RIGHT",4,0);local save=Button(meta,"Save",58);save:SetPoint("LEFT",meta.maxLevel,"RIGHT",8,0);save:SetScript("OnClick",function()local route=HC:GetSelectedRoute();local challenge=HCChallengerChallenges[HC.State.challengeIndex];HC:UpdateRoute(route,meta.name:GetText(),challenge.id,HC.Factions[HC.State.factionIndex],HC.Classes[HC.State.classIndex],meta.minLevel:GetText(),meta.maxLevel:GetText(),meta.description:GetText());meta.loadedRouteId=nil end)
 meta.status=Text(meta,"","GameFontDisableSmall",.62,.59,.53);meta.status:SetPoint("BOTTOMLEFT",meta,"BOTTOMLEFT",12,9);meta.status:SetWidth(480);meta.status:SetJustifyH("LEFT");local publish=Button(meta,"Publish",72);publish:SetPoint("BOTTOMRIGHT",meta,"BOTTOMRIGHT",-10,7);publish:SetScript("OnClick",function()HC:PublishRoute(HC:GetSelectedRoute())end);local guide=Button(meta,"Start guide",88);guide:SetPoint("RIGHT",publish,"LEFT",-6,0);guide:SetScript("OnClick",function()HC:ActivateRoute(HC:GetSelectedRoute(),"local")end)

 local steps=Panel(root);steps:SetPoint("TOPLEFT",root,"TOPLEFT",228,-136);steps:SetWidth(672);steps:SetHeight(194);local sh=Text(steps,"ROUTE STEPS","GameFontNormal",1,.82,.2);sh:SetPoint("TOPLEFT",steps,"TOPLEFT",10,-9);steps.count=Text(steps,"","GameFontDisableSmall",.62,.59,.53);steps.count:SetPoint("TOPRIGHT",steps,"TOPRIGHT",-10,-11);steps.rows={}
 for i=1,self.STEP_ROWS do local r=CreateFrame("Button",nil,steps);r:SetWidth(646);r:SetHeight(25);r:SetPoint("TOPLEFT",steps,"TOPLEFT",12,-31-((i-1)*26));r:SetBackdrop(PANEL);r:SetBackdropColor(math.mod(i,2)==0 and .05 or .025,.025,.02,.78);r.text=Text(r,"");r.text:SetPoint("LEFT",r,"LEFT",6,0);r.text:SetWidth(634);r.text:SetJustifyH("LEFT");r:SetScript("OnClick",function()if this.stepIndex then HC.State.stepIndex=this.stepIndex;HC:RefreshUI()end end);steps.rows[i]=r end
 local newerStep=Button(steps,"Newer",60);newerStep:SetPoint("BOTTOMLEFT",steps,"BOTTOMLEFT",10,7);newerStep:SetScript("OnClick",function()HC.State.stepOffset=HC.State.stepOffset-HC.STEP_ROWS;if HC.State.stepOffset<0 then HC.State.stepOffset=0 end;HC:RefreshUI()end);local olderStep=Button(steps,"Older",60);olderStep:SetPoint("LEFT",newerStep,"RIGHT",5,0);olderStep:SetScript("OnClick",function()HC.State.stepOffset=HC.State.stepOffset+HC.STEP_ROWS;HC:RefreshUI()end);local up=Button(steps,"Up",48);up:SetPoint("LEFT",olderStep,"RIGHT",20,0);up:SetScript("OnClick",function()HC:MoveStep(HC:GetSelectedRoute(),HC.State.stepIndex,-1)end);local down=Button(steps,"Down",52);down:SetPoint("LEFT",up,"RIGHT",5,0);down:SetScript("OnClick",function()HC:MoveStep(HC:GetSelectedRoute(),HC.State.stepIndex,1)end);local remove=Button(steps,"Remove step",90);remove:SetPoint("LEFT",down,"RIGHT",5,0);remove:SetScript("OnClick",function()HC:RemoveStep(HC:GetSelectedRoute(),HC.State.stepIndex)end)

 local editor=Panel(root);editor:SetPoint("TOPLEFT",root,"TOPLEFT",228,-340);editor:SetWidth(672);editor:SetHeight(90);local eh=Text(editor,"ADD MANUAL STEP","GameFontNormal",1,.82,.2);eh:SetPoint("TOPLEFT",editor,"TOPLEFT",10,-9);editor.type=Button(editor,"Travel",92);editor.type:SetPoint("TOPLEFT",editor,"TOPLEFT",10,-31);editor.type:SetScript("OnClick",function()HC.State.stepTypeIndex=HC.State.stepTypeIndex+1;if HC.State.stepTypeIndex>table.getn(HC.StepTypes)then HC.State.stepTypeIndex=1 end;this:SetText(HC.StepTypes[HC.State.stepTypeIndex])end);editor.title=Edit(editor,195,48);editor.title:SetPoint("LEFT",editor.type,"RIGHT",6,0);editor.note=Edit(editor,270,80);editor.note:SetPoint("LEFT",editor.title,"RIGHT",6,0);local add=Button(editor,"Add",62);add:SetPoint("LEFT",editor.note,"RIGHT",6,0);add:SetScript("OnClick",function()HC:AddStep(HC:GetSelectedRoute(),HC.StepTypes[HC.State.stepTypeIndex],editor.title:GetText(),editor.note:GetText(),nil,nil,nil);editor.title:SetText("");editor.note:SetText("")end)
 local help=Text(editor,"Add + position captures your current zone coordinates once. For Trial kill/grind steps, set the intended mob level range.","GameFontDisableSmall",.61,.58,.52);help:SetPoint("BOTTOMLEFT",editor,"BOTTOMLEFT",10,8);editor.minLevel=Edit(editor,34,3);editor.minLevel:SetPoint("BOTTOMRIGHT",editor,"BOTTOMRIGHT",-183,5);editor.maxLevel=Edit(editor,34,3);editor.maxLevel:SetPoint("LEFT",editor.minLevel,"RIGHT",4,0);local addPos=Button(editor,"Add + position",104);addPos:SetPoint("LEFT",editor.maxLevel,"RIGHT",6,0);addPos:SetScript("OnClick",function()HC:AddStep(HC:GetSelectedRoute(),HC.StepTypes[HC.State.stepTypeIndex],editor.title:GetText(),editor.note:GetText(),1,editor.minLevel:GetText(),editor.maxLevel:GetText());editor.title:SetText("");editor.note:SetText("")end)
 root.left=left;root.meta=meta;root.steps=steps;root.editor=editor;self.Frames.my=root;return root
end

function HC:GetCommunityDisplayList()
 local output={};local catalog=self:GetCatalogList();local used={};local i
 for i=1,table.getn(catalog)do local item=catalog[i];local route=self:GetCommunityRoute(item.author,item.id);local copy={};local k,v;for k,v in pairs(item)do copy[k]=v end;copy.route=route;used[item.key]=1;table.insert(output,copy)end
 for i=1,table.getn(self.DB.communityRoutes)do local route=self.DB.communityRoutes[i];local key=self:NameKey(route.author).."~"..route.id;if not used[key]then table.insert(output,{key=key,id=route.id,author=route.author,revision=route.revision,name=route.name,challengeId=route.challengeId,faction=route.faction,className=route.className,minLevel=route.minLevel,maxLevel=route.maxLevel,stepCount=table.getn(route.steps),description=route.description,route=route,downloadedOnly=1})end end
 table.sort(output,function(a,b)if a.challengeId~=b.challengeId then return(a.challengeId or"")<(b.challengeId or"")end;return(a.name or"")<(b.name or"")end);return output
end
function HC:GetSelectedCommunityDisplay()local list=self:GetCommunityDisplayList();local i;for i=1,table.getn(list)do if list[i].key==self.State.communityKey then return list[i]end end;return nil end
function HC:CreateCommunityPanel(parent)
 local root=CreateFrame("Frame",nil,parent);root:SetAllPoints(parent);local top=Panel(root);top:SetPoint("TOPLEFT",root,"TOPLEFT",0,0);top:SetWidth(900);top:SetHeight(58);top.network=Button(top,"Network OFF",105);top.network:SetPoint("LEFT",top,"LEFT",10,0);top.network:SetScript("OnClick",function()HC.DB.settings.networkEnabled=not HC.DB.settings.networkEnabled;if HC.DB.settings.networkEnabled then HC:JoinNetwork()else HC:StopNetwork()end;HC:RefreshUI()end);top.status=Text(top,"",nil,.88,.72,.3);top.status:SetPoint("LEFT",top.network,"RIGHT",12,0);top.status:SetWidth(650);top.status:SetJustifyH("LEFT");local hint=Text(top,"Publishing advertises metadata; route steps are sent only after a player's Download click.","GameFontDisableSmall",.58,.56,.5);hint:SetPoint("BOTTOMLEFT",top,"BOTTOMLEFT",12,5)
 local listPanel=Panel(root);listPanel:SetPoint("TOPLEFT",root,"TOPLEFT",0,-68);listPanel:SetWidth(900);listPanel:SetHeight(300);local head=Text(listPanel,"COMMUNITY ROUTES","GameFontNormal",1,.82,.2);head:SetPoint("TOPLEFT",listPanel,"TOPLEFT",10,-9);listPanel.count=Text(listPanel,"","GameFontDisableSmall",.62,.59,.53);listPanel.count:SetPoint("TOPRIGHT",listPanel,"TOPRIGHT",-10,-11);listPanel.rows={};local i
 for i=1,self.COMMUNITY_ROWS do local r=CreateFrame("Button",nil,listPanel);r:SetWidth(874);r:SetHeight(25);r:SetPoint("TOPLEFT",listPanel,"TOPLEFT",12,-32-((i-1)*27));r:SetBackdrop(PANEL);r:SetBackdropColor(math.mod(i,2)==0 and .05 or .025,.025,.02,.78);r.text=Text(r,"");r.text:SetPoint("LEFT",r,"LEFT",6,0);r.text:SetWidth(860);r.text:SetJustifyH("LEFT");r:SetScript("OnClick",function()if this.communityKey then HC.State.communityKey=this.communityKey;HC:RefreshUI()end end);listPanel.rows[i]=r end
 local newer=Button(listPanel,"Newer",64);newer:SetPoint("BOTTOMLEFT",listPanel,"BOTTOMLEFT",10,7);newer:SetScript("OnClick",function()HC.State.communityOffset=HC.State.communityOffset-HC.COMMUNITY_ROWS;if HC.State.communityOffset<0 then HC.State.communityOffset=0 end;HC:RefreshUI()end);local older=Button(listPanel,"Older",64);older:SetPoint("LEFT",newer,"RIGHT",5,0);older:SetScript("OnClick",function()HC.State.communityOffset=HC.State.communityOffset+HC.COMMUNITY_ROWS;HC:RefreshUI()end)
 local detail=Panel(root);detail:SetPoint("TOPLEFT",root,"TOPLEFT",0,-378);detail:SetWidth(900);detail:SetHeight(52);detail.text=Text(detail,"Select an advertised or downloaded route.",nil,.82,.79,.71);detail.text:SetPoint("LEFT",detail,"LEFT",12,0);detail.text:SetWidth(555);detail.text:SetJustifyH("LEFT");local download=Button(detail,"Download",82);download:SetPoint("RIGHT",detail,"RIGHT",-208,0);download:SetScript("OnClick",function()HC:RequestRoute(HC:GetSelectedCommunityDisplay())end);local start=Button(detail,"Start guide",88);start:SetPoint("LEFT",download,"RIGHT",6,0);start:SetScript("OnClick",function()local item=HC:GetSelectedCommunityDisplay();if item and item.route then HC:ActivateRoute(item.route,"community")else HC:Print("download the route first.")end end);local copy=Button(detail,"Copy to mine",98);copy:SetPoint("LEFT",start,"RIGHT",6,0);copy:SetScript("OnClick",function()local item=HC:GetSelectedCommunityDisplay();if item and item.route then HC:CopyCommunityRoute(item.route)else HC:Print("download the route first.")end end)
 root.top=top;root.list=listPanel;root.detail=detail;self.Frames.community=root;return root
end
function HC:CreateChallengesPanel(parent)
 local root=CreateFrame("Frame",nil,parent);root:SetAllPoints(parent);local list=Panel(root);list:SetPoint("TOPLEFT",root,"TOPLEFT",0,0);list:SetWidth(260);list:SetHeight(430);local h=Text(list,"SERVER CHALLENGES","GameFontNormal",1,.82,.2);h:SetPoint("TOP",list,"TOP",0,-10);list.rows={};local i
 for i=1,table.getn(HCChallengerChallenges)do local c=HCChallengerChallenges[i];local b=CreateFrame("Button",nil,list);b:SetWidth(234);b:SetHeight(27);b:SetPoint("TOPLEFT",list,"TOPLEFT",12,-33-((i-1)*29));b:SetBackdrop(PANEL);b:SetBackdropColor(math.mod(i,2)==0 and .05 or .025,.025,.02,.78);b.icon=b:CreateTexture(nil,"ARTWORK");b.icon:SetTexture(c.icon);b.icon:SetWidth(19);b.icon:SetHeight(19);b.icon:SetPoint("LEFT",b,"LEFT",5,0);b.text=Text(b,c.name);b.text:SetPoint("LEFT",b.icon,"RIGHT",6,0);b.challengeIndex=i;b:SetScript("OnClick",function()HC.State.challengeView=this.challengeIndex;HC:RefreshUI()end);list.rows[i]=b end
 local detail=Panel(root);detail:SetPoint("TOPLEFT",root,"TOPLEFT",270,0);detail:SetWidth(630);detail:SetHeight(430);detail.icon=detail:CreateTexture(nil,"ARTWORK");detail.icon:SetWidth(48);detail.icon:SetHeight(48);detail.icon:SetPoint("TOPLEFT",detail,"TOPLEFT",20,-20);detail.title=Text(detail,"","GameFontNormalLarge",1,.72,.18);detail.title:SetPoint("LEFT",detail.icon,"RIGHT",14,5);detail.subtitle=Text(detail,"Static profile from the supplied server challenge screenshot","GameFontDisableSmall",.6,.57,.5);detail.subtitle:SetPoint("TOPLEFT",detail.title,"BOTTOMLEFT",0,-5);local rh=Text(detail,"RULE SUMMARY","GameFontNormal",1,.82,.2);rh:SetPoint("TOPLEFT",detail,"TOPLEFT",22,-92);detail.rules=Text(detail,"",nil,.9,.87,.78);detail.rules:SetPoint("TOPLEFT",detail,"TOPLEFT",22,-116);detail.rules:SetWidth(584);detail.rules:SetJustifyH("LEFT");local ah=Text(detail,"ROUTE-BUILDING ADVICE","GameFontNormal",1,.82,.2);ah:SetPoint("TOPLEFT",detail,"TOPLEFT",22,-205);detail.advice=Text(detail,"",nil,.9,.87,.78);detail.advice:SetPoint("TOPLEFT",detail,"TOPLEFT",22,-230);detail.advice:SetWidth(584);detail.advice:SetJustifyH("LEFT");local warning=Text(detail,"HC Challenger does not enforce server rules. Verify current rules in-game or on the server site.","GameFontDisableSmall",1,.45,.25);warning:SetPoint("BOTTOMLEFT",detail,"BOTTOMLEFT",22,54);local create=Button(detail,"Create route for this challenge",205);create:SetPoint("BOTTOMLEFT",detail,"BOTTOMLEFT",22,18);create:SetScript("OnClick",function()local c=HCChallengerChallenges[HC.State.challengeView]or HCChallengerChallenges[1];local r=HC:CreateRoute(c.name.." route",c.id);if r then HC.State.tab="My Routes";HC:SelectRoute(r.id)end end)
 root.list=list;root.detail=detail;self.Frames.challenges=root;return root
end
function HC:CreateGuideFrame()
 local f=CreateFrame("Frame","HCChallengerGuideFrame",UIParent);f:SetWidth(410);f:SetHeight(238);f:SetFrameStrata("DIALOG");f:SetMovable(1);f:EnableMouse(1);f:SetBackdrop(BACKDROP);f:RegisterForDrag("LeftButton");f:SetScript("OnDragStart",function()this:StartMoving()end);f:SetScript("OnDragStop",function()this:StopMovingOrSizing();HC:SavePosition(this,"guidePosition")end);f.route=Text(f,"No active route","GameFontNormal",1,.82,.2);f.route:SetPoint("TOPLEFT",f,"TOPLEFT",18,-17);f.route:SetWidth(320);f.route:SetJustifyH("LEFT");f.counter=Text(f,"","GameFontDisableSmall",.62,.59,.53);f.counter:SetPoint("TOPRIGHT",f,"TOPRIGHT",-50,-20);local close=Button(f,"X",28);close:SetPoint("TOPRIGHT",f,"TOPRIGHT",-13,-12);close:SetScript("OnClick",function()f:Hide()end);f.step=Text(f,"Choose a route in HC Challenger.","GameFontNormalLarge",.95,.92,.84);f.step:SetPoint("TOPLEFT",f,"TOPLEFT",18,-51);f.step:SetWidth(370);f.step:SetJustifyH("LEFT");f.location=Text(f,"");f.location:SetPoint("TOPLEFT",f.step,"BOTTOMLEFT",0,-8);f.location:SetWidth(370);f.location:SetJustifyH("LEFT");f.distance=Text(f,"","GameFontDisableSmall",.64,.62,.56);f.distance:SetPoint("TOPLEFT",f.location,"BOTTOMLEFT",0,-5);f.note=Text(f,"");f.note:SetPoint("TOPLEFT",f.distance,"BOTTOMLEFT",0,-8);f.note:SetWidth(370);f.note:SetJustifyH("LEFT");f.challenge=Text(f,"",nil,1,.78,.25);f.challenge:SetPoint("TOPLEFT",f,"TOPLEFT",18,-149);f.challenge:SetWidth(370);f.challenge:SetJustifyH("LEFT");local prev=Button(f,"Previous",78);prev:SetPoint("BOTTOMLEFT",f,"BOTTOMLEFT",18,16);prev:SetScript("OnClick",function()HC:PreviousGuide()end);local skip=Button(f,"Skip",62);skip:SetPoint("LEFT",prev,"RIGHT",7,0);skip:SetScript("OnClick",function()HC:AdvanceGuide(nil)end);local complete=Button(f,"Complete + next",120);complete:SetPoint("BOTTOMRIGHT",f,"BOTTOMRIGHT",-18,16);complete:SetScript("OnClick",function()HC:AdvanceGuide(1)end);self.Frames.guide=f;table.insert(UISpecialFrames,"HCChallengerGuideFrame");f:Hide()
end
function HC:CreateMainFrame()
 local f=CreateFrame("Frame","HCChallengerFrame",UIParent);f:SetWidth(940);f:SetHeight(570);f:SetFrameStrata("DIALOG");f:SetMovable(1);f:EnableMouse(1);f:SetBackdrop(BACKDROP);f:RegisterForDrag("LeftButton");f:SetScript("OnDragStart",function()this:StartMoving()end);f:SetScript("OnDragStop",function()this:StopMovingOrSizing();HC:SavePosition(this,"position")end);local title=Text(f,self.COLORED_NAME,"GameFontNormalLarge");title:SetPoint("TOP",f,"TOP",0,-17);local subtitle=Text(f,"Build, play and share manual challenge routes  |  v"..self.VERSION,"GameFontDisableSmall",.62,.58,.5);subtitle:SetPoint("TOP",title,"BOTTOM",0,-2);local close=Button(f,"X",28);close:SetPoint("TOPRIGHT",f,"TOPRIGHT",-14,-13);close:SetScript("OnClick",function()HC:Close()end);f.tabs={};local names={"My Routes","Community","Challenges"};local x=20;local i;for i=1,table.getn(names)do local b=Button(f,names[i],110);b:SetPoint("TOPLEFT",f,"TOPLEFT",x,-62);b.tabName=names[i];b:SetScript("OnClick",function()HC:SetTab(this.tabName)end);f.tabs[names[i]]=b;x=x+116 end;local content=CreateFrame("Frame",nil,f);content:SetPoint("TOPLEFT",f,"TOPLEFT",20,-101);content:SetWidth(900);content:SetHeight(430);self.Frames.main=f;self.Frames.content=content;self:CreateMyPanel(content);self:CreateCommunityPanel(content);self:CreateChallengesPanel(content);table.insert(UISpecialFrames,"HCChallengerFrame");f:Hide()
end
function HC:SetTab(name)
 if name~="My Routes"and name~="Community"and name~="Challenges"then return end;self.State.tab=name;self.Frames.my:Hide();self.Frames.community:Hide();self.Frames.challenges:Hide();if name=="My Routes"then self.Frames.my:Show()elseif name=="Community"then self.Frames.community:Show()else self.Frames.challenges:Show()end;self:RefreshUI()
end
function HC:RefreshMyPanel()
 local f=self.Frames.my;local routes=self.DB.routes;local total=table.getn(routes);local max=total-self.ROUTE_ROWS;if max<0 then max=0 end;if self.State.routeOffset>max then self.State.routeOffset=max end;local i
 for i=1,self.ROUTE_ROWS do local route=routes[self.State.routeOffset+i];local row=f.left.rows[i];if route then row.routeId=route.id;row.name:SetText(route.name);row.meta:SetText(self:GetChallengeName(route.challengeId).."  |  "..table.getn(route.steps).." steps");if route.id==self.State.routeId then row:SetBackdropBorderColor(1,.65,.15,1)else row:SetBackdropBorderColor(.25,.22,.17,1)end;row:Show()else row.routeId=nil;row:Hide()end end
 local route=self:GetSelectedRoute();if route and f.loadedRouteId~=route.id then f.loadedRouteId=route.id;f.meta.name:SetText(route.name);f.meta.description:SetText(route.description or"");f.meta.minLevel:SetText(tostring(route.minLevel or 1));f.meta.maxLevel:SetText(tostring(route.maxLevel or 60));local c,ci=self:GetChallenge(route.challengeId);self.State.challengeIndex=ci;f.meta.challenge:SetText(c.name);for i=1,table.getn(self.Factions)do if self.Factions[i]==route.faction then self.State.factionIndex=i end end;for i=1,table.getn(self.Classes)do if self.Classes[i]==route.className then self.State.classIndex=i end end;f.meta.faction:SetText(self.Factions[self.State.factionIndex]);f.meta.class:SetText(self.Classes[self.State.classIndex])end
 if route then local publish=route.publishedRevision and("published r"..route.publishedRevision)or"private";if route.dirty and route.publishedRevision then publish=publish.." / edits not republished"end;f.meta.status:SetText("Revision "..tostring(route.revision or 1).."  |  "..publish);local count=table.getn(route.steps);local stepMax=count-self.STEP_ROWS;if stepMax<0 then stepMax=0 end;if self.State.stepOffset>stepMax then self.State.stepOffset=stepMax end;f.steps.count:SetText(count.." / "..self.MAX_STEPS.." steps");for i=1,self.STEP_ROWS do local index=self.State.stepOffset+i;local step=route.steps[index];local row=f.steps.rows[i];if step then row.stepIndex=index;local coords=step.x and(" "..math.floor(step.x*100)..","..math.floor(step.y*100))or" zone-only";row.text:SetText(index..". "..string.upper(step.type).."  |  "..step.title.."  |  "..step.zone..coords.."  |  mobs L"..tostring(step.minLevel or"?").."-"..tostring(step.maxLevel or"?"));if index==self.State.stepIndex then row:SetBackdropBorderColor(1,.65,.15,1)else row:SetBackdropBorderColor(.25,.22,.17,1)end;row:Show()else row.stepIndex=nil;row:Hide()end end
 else f.meta.status:SetText("Create a route to begin.");f.steps.count:SetText("0 steps");for i=1,self.STEP_ROWS do f.steps.rows[i]:Hide()end end
end
function HC:RefreshCommunityPanel()
 local f=self.Frames.community;f.top.network:SetText(self.DB.settings.networkEnabled and"Network ON"or"Network OFF");f.top.status:SetText(self:NetworkStatus());local list=self:GetCommunityDisplayList();local total=table.getn(list);local max=total-self.COMMUNITY_ROWS;if max<0 then max=0 end;if self.State.communityOffset>max then self.State.communityOffset=max end;f.list.count:SetText(total.." visible route(s)");local i
 for i=1,self.COMMUNITY_ROWS do local item=list[self.State.communityOffset+i];local row=f.list.rows[i];if item then row.communityKey=item.key;local state=item.route and"DOWNLOADED"or(item.downloadedOnly and"SAVED"or"AVAILABLE");row.text:SetText(state.."  |  "..item.name.."  |  "..self:GetChallengeName(item.challengeId).."  |  L"..item.minLevel.."-"..item.maxLevel.."  |  "..item.stepCount.." steps  |  by "..item.author);if item.key==self.State.communityKey then row:SetBackdropBorderColor(1,.65,.15,1)else row:SetBackdropBorderColor(.25,.22,.17,1)end;row:Show()else row.communityKey=nil;row:Hide()end end
 local selected=self:GetSelectedCommunityDisplay();if selected then f.detail.text:SetText(selected.name.." — "..(selected.description or"").."  |  revision "..tostring(selected.revision)..(selected.route and"  |  ready to play"or"  |  metadata only; click Download"))else f.detail.text:SetText("No community route selected. Both publisher and downloader must be online during transfer.")end
end
function HC:RefreshChallengesPanel()
 local f=self.Frames.challenges;local selected=HCChallengerChallenges[self.State.challengeView]or HCChallengerChallenges[1];local i;for i=1,table.getn(f.list.rows)do local row=f.list.rows[i];if i==self.State.challengeView then row:SetBackdropBorderColor(1,.65,.15,1)else row:SetBackdropBorderColor(.25,.22,.17,1)end end;f.detail.icon:SetTexture(selected.icon);f.detail.title:SetText(selected.name);f.detail.rules:SetText(selected.rules);f.detail.advice:SetText(selected.advice)
end
function HC:RefreshUI()
 if not self.DB or not self.Frames.main then return end;local name,button;for name,button in pairs(self.Frames.main.tabs)do if name==self.State.tab then button:LockHighlight()else button:UnlockHighlight()end end;if self.State.tab=="My Routes"then self:RefreshMyPanel()elseif self.State.tab=="Community"then self:RefreshCommunityPanel()else self:RefreshChallengesPanel()end;self:RefreshGuide()
end
function HC:RestoreUISettings()
 if not self.DB then return end;local p=self.DB.settings.position;self.Frames.main:ClearAllPoints();self.Frames.main:SetPoint(p.point or"CENTER",UIParent,p.relPoint or"CENTER",p.x or 0,p.y or 0);local g=self.DB.settings.guidePosition;self.Frames.guide:ClearAllPoints();self.Frames.guide:SetPoint(g.point or"RIGHT",UIParent,g.relPoint or"RIGHT",g.x or-30,g.y or 40);self:SetMinimapAngle(self.DB.settings.minimapAngle);if self.DB.settings.minimap then self.Frames.minimap:Show()else self.Frames.minimap:Hide()end;self:SetTab(self.State.tab)
end
function HC:ShowGuide()self.Frames.guide:Show();self:RefreshGuide()end
function HC:Open()self:RefreshUI();self.Frames.main:Show()end
function HC:Close()self.Frames.main:Hide()end
function HC:Toggle()if self.Frames.main:IsShown()then self:Close()else self:Open()end end

HC:CreateMainFrame();HC:CreateGuideFrame();HC:CreateMinimapButton()
SLASH_HCCHALLENGER1="/hcc";SLASH_HCCHALLENGER2="/hcchallenger"
SlashCmdList["HCCHALLENGER"]=function(message)
 local raw=HC:Trim(message or"",100);local lower=string.lower(raw);if lower=="network on"then HC.DB.settings.networkEnabled=1;HC:JoinNetwork()elseif lower=="network off"then HC.DB.settings.networkEnabled=nil;HC:StopNetwork()elseif lower=="guide"then HC:ShowGuide()elseif lower=="community"then HC:Open();HC:SetTab("Community")elseif lower=="challenges"then HC:Open();HC:SetTab("Challenges")elseif lower=="minimap"then HC.DB.settings.minimap=not HC.DB.settings.minimap;HC:RestoreUISettings()elseif string.sub(lower,1,4)=="new "then HC:CreateRoute(string.sub(raw,5),"STANDARD");HC:Open();HC:SetTab("My Routes")else HC:Toggle()end;if HC.RefreshUI then HC:RefreshUI()end
end
local events=CreateFrame("Frame",nil,UIParent);local names={"VARIABLES_LOADED","PLAYER_ENTERING_WORLD","PLAYER_TARGET_CHANGED","PLAYER_LEVEL_UP","ZONE_CHANGED","ZONE_CHANGED_NEW_AREA","CHAT_MSG_CHANNEL","CHAT_MSG_CHANNEL_NOTICE"};local i;for i=1,table.getn(names)do events:RegisterEvent(names[i])end;events:SetScript("OnEvent",function()HC:OnEvent(event,arg1,arg2,arg9)end);events:SetScript("OnUpdate",function()HC:NetworkUpdate()end)
